server:
  port: 8030
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    provider: /p/**

# localhost:8030/p/student/findAll = localhost:8010/student/findAll
# p = localhost:8010
