server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mofeisike/Spring-Cloud-Demo.git
          searchPaths: configs
          username: mofeisike
          password: 15014359831a
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/